### ISSUE TITLE
PLUMED WRONG 

### ISSUE THREAD

**Issue by Wang-createe** [Zhang-pchao/GlycineTautomerism#1]
章博士您好，在我按照您github上的教程将您的分享在github上的 VORONOID2.cpp, VORONOIS1.cpp, VORONOIC0.cpp全部添加到plumed/src/colvar后编译之后，依旧无法实现您Enhanced_Sampling/final_MD中给的例子，plumed报错为：I cannot understand line: VORONOI...........请问是仅支持plumed v_2.8.1吗？还是不支持与lammps patch？如果可以的话还请您帮忙解答，十分感谢并期待您的回信

**Comment by Zhang-pchao** [comment]
I commented out some auxiliary CVs. Please try again with the [input.plumed](https://github.com/Zhang-pchao/GlycineTautomerism/blob/main/Enhanced_Sampling/final_MD/input.plumed)

**Comment by Zhang-pchao** [comment]
Follow [here](https://github.com/Zhang-pchao/plumed-feedstock/tree/devel) to update plumed version with [Voronoi CVs](https://github.com/Zhang-pchao/GlycineTautomerism/tree/main/Voronoi_collective_variables) in deepmd conda environment will fix this issue.
